In [3]:
import numpy as np


In [3]:
# ques 1
#a
a= np.array([1,2,3,6,4,5]);
rev_arr = np.flip(a)
print("Reversed arr: ",rev_arr)

Reversed arr:  [5 4 6 3 2 1]


In [5]:
#b
arr = np.array([[1,2,3],[2,4,5],[1,2,3]]);
print("Original arr:",arr)
flaten_Arr = arr.flatten()
print("Flattened arr: ", flaten_Arr);

Original arr: [[1 2 3]
 [2 4 5]
 [1 2 3]]
Flattened arr:  [1 2 3 2 4 5 1 2 3]


In [7]:
#c
a1 =  np.array([[1, 2], [3, 4]]) ;
a2 =  np.array([[1, 2], [3, 4]]) ;
print("Equal arrays : " , np.array_equal(a1,a2))

Equal arrays :  True


In [9]:
# d
x = np.array([1,2,3,4,5,1,2,1,1,1]) 
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ]) 
most_freq_x = np.bincount(x).argmax()
x_indice = np.where( x == most_freq_x)[0]
most_freq_y = np.bincount(y).argmax()
y_indice = np.where( y == most_freq_y)[0]
print("Most freq in x: " ,most_freq_x, "At: ",x_indice);
print("Most freq in y: " ,most_freq_y, "At: ",y_indice);

Most freq in x:  1 At:  [0 5 7 8 9]
Most freq in y:  1 At:  [0 1 2]


In [10]:
#e
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
TotSum = gfg.sum()
sum_row = gfg.sum(axis=1)
sum_col = gfg.sum(axis = 0)
print("Sum = ", TotSum)
print("Sum row = ", sum_row)
print("Sum col = ", sum_col)



Sum =  45
Sum row =  [[14]
 [16]
 [15]]
Sum col =  [[20  9 16]]


In [11]:
#f
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
diag_sum = np.trace(n_array)
eigen_values, eigen_vectors = np.linalg.eig(n_array)
inverse_matrix = np.linalg.inv(n_array)
determinant_matrix = np.linalg.det(n_array)
print("Sum of Diagonal:", diag_sum)
print("Eigen Values:", eigen_values)
print("Eigen Vectors:\n", eigen_vectors)
print("Inverse Matrix:\n", inverse_matrix)
print("Determinant:", determinant_matrix)

Sum of Diagonal: 176
Eigen Values: [98.16835147 28.097044   49.73460452]
Eigen Vectors:
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse Matrix:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant: 137180.0000000001


In [16]:
#g
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]]) 
mul1 = np.dot(p1,q1)
cov1 = np.cov(p1,q1)
print("Multiplication: ",mul1)
print("Covariance: ", cov1)

p2 = np.array( [[1, 2], [2, 3], [4, 5]])
q2 = np.array( [[4, 5, 1], [6, 7, 2]] ) 
mul2 = np.dot(p2,q2)
cov2 = np.cov(p2,rowvar=False,bias=True)
print("Multiplication: ",mul2)
print("Covariance: ", cov2)

Multiplication:  [[16 19]
 [26 31]]
Covariance:  [[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]
Multiplication:  [[16 19  5]
 [26 31  8]
 [46 55 14]]
Covariance:  [[1.55555556 1.55555556]
 [1.55555556 1.55555556]]


In [19]:
#h
x = np.array([[2, 3, 4], [3, 2, 9]]);
y = np.array([[1, 5, 0], [5, 10, 3]]);
print("Inner product: ", np.inner(x,y))
print("Outer product: ", np.outer(x,y))
print("Cross product: ", np.cross(x,y))
print("Cartesian product: ", np.tensordot(x, y, axes=0))

Inner product:  [[17 52]
 [13 62]]
Outer product:  [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cross product:  [[-20   4   7]
 [-84  36  20]]
Cartesian product:  [[[[ 2 10  0]
   [10 20  6]]

  [[ 3 15  0]
   [15 30  9]]

  [[ 4 20  0]
   [20 40 12]]]


 [[[ 3 15  0]
   [15 30  9]]

  [[ 2 10  0]
   [10 20  6]]

  [[ 9 45  0]
   [45 90 27]]]]


In [23]:
# ques 2
# a
# i.
array = np.array([[1, -2, 3],[-4, 5, -6]]) 
abs_arr= np.abs(array)
print(abs_arr)
print("**********************")
# ii.
flatten = array.flatten()
print("Flattened array: ", flatten)
percentile = np.percentile( array , [25,50,75] )
percentile_col = np.percentile(array, [25,50,75] , axis = 0)
percentile_row = np.percentile(array, [25,50,75] , axis = 1)
print("percentile flattened:",percentile)
print("percentile column-wise:",percentile_col)
print("percentile row-wise:",percentile_row)
print("**********************")

# iii.
mean_flat = np.mean(array)
med_flat = np.median(array)
sd_flat = np.std(array)
print(f"flatten:\n mean: {mean_flat} \n meadian: {med_flat} \n sd: {sd_flat}")

mean_col = np.mean(array,axis=0)
med_col = np.median(array,axis=0)
sd_col = np.std(array,axis=0)
print(f"Col-wise:\n mean: {mean_col} \n meadian: {med_col} \n sd: {sd_col}")

mean_row = np.mean(array,axis=1)
med_row = np.median(array,axis=1)
sd_row = np.std(array,axis=1)
print(f"Row-wise:\n mean: {mean_row} \n meadian: {med_row} \n sd: {sd_row}")


[[1 2 3]
 [4 5 6]]
**********************
Flattened array:  [ 1 -2  3 -4  5 -6]
percentile flattened: [-3.5 -0.5  2.5]
percentile column-wise: [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
percentile row-wise: [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
**********************
flatten:
 mean: -0.5 
 meadian: -0.5 
 sd: 3.8622100754188224
Col-wise:
 mean: [-1.5  1.5 -1.5] 
 meadian: [-1.5  1.5 -1.5] 
 sd: [2.5 3.5 4.5]
Row-wise:
 mean: [ 0.66666667 -1.66666667] 
 meadian: [ 1. -4.] 
 sd: [2.05480467 4.78423336]


In [26]:
#b
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
floor = np.floor(a)
ceiling = np.ceil(a)
truncate = np.trunc(a)
rounded = np.round(a)
print(f"floor:{floor}\n ceiling:{ceiling}\n truncated values:{truncate}\n rounded values:{rounded}")


floor:[-2. -2. -1.  0.  1.  1.  3.]
 ceiling:[-1. -1. -0.  1.  2.  2.  3.]
 truncated values:[-1. -1. -0.  0.  1.  1.  3.]
 rounded values:[-2. -2. -0.  0.  2.  2.  3.]


In [27]:
# ques 3
#a
arr = np.array([10, 52, 62, 16, 16, 54, 453])
sortedArr = np.sort(arr)
print("Sorted array: ", sortedArr)
print("Indices of sorted array: ", np.argsort(arr))
print("4 smallest elements :", np.sort(arr)[:4])
print("5 largest elements  :", np.sort(arr)[-5:])


Sorted array:  [ 10  16  16  52  54  62 453]
Indices of sorted array:  [0 3 4 1 5 2 6]
4 smallest elements : [10 16 16 52]
5 largest elements  : [ 16  52  54  62 453]


In [28]:
#b

arr1 =  np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
int_only = arr1[ arr1 == np.floor(arr1) ]
print("Integer elements only: ", int_only)
float_only = arr1[ arr1 != np.floor(arr1) ]
print("Float elements only: ", float_only)

Integer elements only:  [1. 2. 3. 2.]
Float elements only:  [1.2 2.2]


In [30]:
# ques 4
import cv2
import numpy as np

def img_to_array(path, save_path="image_array.txt"):
    
    img = cv2.imread(path, cv2.IMREAD_UNCHANGED)
    if img is None:
        print("Error: Image not found!")
        return
    if len(img.shape) == 2:  
        print("Grayscale Image detected")
    elif len(img.shape) == 3:  
        print("RGB Image detected")
    else:
        print("Unsupported format")
        return
    np.savetxt(save_path, img.reshape(-1, img.shape[-1]) if len(img.shape) == 3 else img, fmt="%d")
    print(f"Image array saved as {save_path}")


img_to_array("img.jpeg")

loaded_array = np.loadtxt("image_array.txt", dtype=np.uint8)

print(loaded_array.shape)
print(loaded_array)


RGB Image detected
Image array saved as image_array.txt
(50274, 3)
[[148  90   0]
 [149  91   0]
 [149  91   0]
 ...
 [ 14  23  20]
 [  3  12   9]
 [  3  12   9]]
